### ISSUE TITLE
Ability to pass Credentials in both .json file way and directly form .env file   

### ISSUE THREAD

**Issue by Shiba-Kar** [rollivier/adonis5-firebase-admin#3]
I store the Firebase admin credentials in .env file ie . ...
```FIREBASE_ADMIN_CERT = { "type":"", "project_id":""}```

**Comment by rollivier** [comment]
Hello, 

First, sorry for the delay in responding, I missed the notification in my emails.

The choice to use the file path follows Firebase's recommendations in the documentation to use a JSON file.

Actually, we don't use this repository anymore and it suffers from a lack of dependency updates that can create security issues. I'm going to change it to unmaintained. If you wish to continue to use it, I invite you to fork it and make your own modifications
